version: '3.8'

services:
  node-app:
    build: .
    image: rocketship-ticket-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/src

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
